name: 'test'

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: setup .env
        run: |
          printf 'ADMIN_KEY=test' > ".env"

      - name: setup firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" | base64 -d > serviceAccountKey.json

      - name: install dependencies
        run: bun install

      - name: test
        run: bun test
