name: 'test'

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: setup .env
        run: |
          printf 'NEIS_API_KEY=${{ secrets.NEIS_API_KEY }}\nADMIN_KEY=test' > ".env"

      - name: setup firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" | base64 -d > serviceAccountKey.json

      - name: install dependencies
        run: deno install

      - name: test
        run: deno test --allow-env
